Error:  RUN bin/npm install: /bin/sh: 1: bin/npm: not found
Reason: bin/npm either isn't in the container, or can't be found by the shell

Solution: change to `npm` instead