Error:  repository does not exist or may require authorization
Reason: Trying to pull image instead of a stage due to misspelled stage name e.g `docker.io/library/assets-builder:latest` instead of `assets_builder_a`

Solution: Set the stage names correctly to `assets_builder_a`