Error: "circular dependency detected on stage: assets_builder"
Reason: The COPY line in `assets_builder` stage had it copying from `assets_builder`, which is the same as the current stage

Suggested solution: Assuming it was meant to be copying the npm install from `node_builder`, change the --from to that stage